name: my_salt
description: MySalt provides AES encryption and decryption with a secure passphrase, ensuring data security with a salt mechanism.
version: 1.0.3+5
repository: https://github.com/ngmduc2012/my_salt.git
funding:
  - https://ko-fi.com/I2I81AEJG8

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  encrypt: ^5.0.3
  crypto: ^3.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

screenshots:
  - description: "avatar image"
    path: avatar.png

topics:
  - password
  - salt-password
  - security
  - security-salt
  - encryption
